[workspace]
resolver = "2"
members = ["day-*"]

[workspace.dependencies]
glam = "0.24.2"
itertools = "0.12.0"
nom = "7.1.3"
rayon = "1.8.0"
rstest = "0.18.2"
rstest_reuse = "0.6.0"
divan = "0.1.3"
miette = { version = "5.10", features = ["fancy"] }
thiserror = "1.0.50"
