work day:
    cargo watch -x "check -p {{day}}" -s "cargo test -p {{day}}" -s "just lint {{day}}"

lint day:
    cargo clippy -p {{day}}

make day:
    cargo generate --path ./_template --name "{{day}}"
